### ISSUE TITLE
Binary Image compressor setup

### ISSUE THREAD

**Issue by 13angs** [13angs/python-basic#1]
## Steps

- setup miniconda env in devcontainer
- install ipykernel for working with jupyter notebook

```bash
pip3 install pandas mysql-connector-python pillow
```

```bash
pip3 install ipykernel -U --user --force-reinstall
```

- select base interpreter

- convert to compose devcontainer
- install the required deps

```bash
pip3 install mysql-connector-python
```

- freeze the deps

```bash
pip freeze > requirements.txt
```
- connect to database
- list all images
- insert images to pandas df 
- display the image
- check if the image endpoint exist or not
- Reupdate the database with new compressed images

## References
1. https://www.youtube.com/watch?v=xZF6zWLz-vY
2. https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html
3. https://stackoverflow.com/questions/273946/how-do-i-resize-an-image-using-pil-and-maintain-its-aspect-ratio
4. https://www.w3resource.com/python-exercises/python-basic-exercise-79.php
5. https://stackoverflow.com/questions/5194057/better-way-to-convert-file-sizes-in-python

**Comment by 13angs** [comment]
```bash
URL can't contain control characters. '/Statics/www/ff8b6dc3-ebf6-4bbe-bc36-5e4dd03b5451product640x640px 2-12.webp' (found at least ' ')
```

**Comment by NareeyaChenu** [comment]
# Error 

``` bash 
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/conda/conda-bld/cffi_1642701102775/work'
```
